spring:
  datasource:
    url: jdbc:h2:mem:.
    driver-class-name: org.h2.Driver
    username: sa
    password: password

server:
  port: 8080

petadoption:
  security:
    client-secret: f3c2557d-ab7c-4b9f-a287-9e5b9b5eb599
    client-id: user-service
