petadoption:
  security:
    auth-server-url: http://localhost:9000/oauth2
    client-secret: 546c5e7b-bd66-4df3-a601-8a31a4bee482
    client-id: api-gateway

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    adoptation:
      path: /adoptation/**
      url: http://adoptation-service:8080
    pet:
      path: /pet/**
      url: http://pet-service:8080
    shelter:
      path: /shelter/**
      url: http://shelter-service:8080
    oauth:
      path: /oauth/**
      url: http://auth-server:9000
    user:
      path: /user/**
      url: http://user-service:8080
