spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

server:
  port: 8080

petadoption:
  security:
    client-secret: 16092ceb-a272-4e02-a286-abc28a3b1b97
    client-id: pet-service
